CSV_COLUMN_CLASSIFICATION = {
    "scholarship_id": ("source_record_id", "DIRECT / PROVENANCE", "Stable imported record identifier."),
    "scholarship_name": ("name", "DIRECT SCHOLARSHIP FACT", "Canonical scholarship name."),
    "provider": ("provider", "DIRECT SCHOLARSHIP FACT", "Canonical provider name."),
    "provider_type": ("legacy_metadata.provider_type", "SOURCE METADATA", "Preserved source classification; not inferred."),
    "source": ("legacy_metadata.source_value", "SOURCE / PROVENANCE", "Preserved dataset source label."),
    "official_source_url": ("official_source_url + provenance", "SOURCE / PROVENANCE", "Preserved URL; not verified."),
    "application_url": ("application_url + provenance", "APPLICATION INFORMATION", "Preserved application URL."),
    "country_of_provider": ("legacy_metadata.country_of_provider", "SOURCE METADATA", "Preserved without guessing."),
    "study_country": ("legacy_metadata.study_country", "ELIGIBILITY INFORMATION", "Preserved source value."),
    "eligible_nationalities": ("legacy_metadata.eligible_nationalities", "ELIGIBILITY INFORMATION", "Preserved; not parsed into rules."),
    "education_level": ("requirements when exact", "ELIGIBILITY INFORMATION", "Only non-generic exact values become equality rules."),
    "study_mode": ("legacy_metadata.study_mode", "ELIGIBILITY INFORMATION", "Preserved; not converted to a rule."),
    "field_of_study": ("legacy_metadata.field_of_study", "ELIGIBILITY INFORMATION", "Preserved; not converted to a rule."),
    "age_min": ("requirements.age min", "ELIGIBILITY INFORMATION", "Rule only when strictly numeric."),
    "age_max": ("requirements.age max", "ELIGIBILITY INFORMATION", "Rule only when strictly numeric."),
    "academic_requirement": ("eligibility_evidence", "DESCRIPTIVE / ELIGIBILITY", "Free text preserved as UNPARSED."),
    "minimum_percentage_or_gpa": ("requirements.academic_percentage min when numeric", "ELIGIBILITY INFORMATION", "Textual values remain evidence only."),
    "family_income_limit": ("requirements.family_income max when numeric", "ELIGIBILITY INFORMATION", "Rule only when strictly numeric."),
    "gender_eligibility": ("requirements.gender equals when specific", "ELIGIBILITY INFORMATION", "Generic Any is not a rule."),
    "category_eligibility": ("legacy_metadata.category_eligibility", "ELIGIBILITY INFORMATION", "Compound categories are preserved, not guessed."),
    "disability_eligibility": ("eligibility_evidence", "DESCRIPTIVE / ELIGIBILITY", "Preserved as unparsed source text."),
    "residency_requirement": ("eligibility_evidence", "DESCRIPTIVE / ELIGIBILITY", "Preserved as unparsed source text."),
    "scholarship_amount": ("amount when strictly numeric", "FUNDING INFORMATION", "Range/text values are not invented as a number."),
    "currency": ("currency", "FUNDING INFORMATION", "Whitespace/casing normalized."),
    "funding_type": ("legacy_metadata.funding_type", "FUNDING INFORMATION", "Preserved source value."),
    "tuition_coverage": ("eligibility_evidence", "DESCRIPTIVE", "Preserved as unparsed text."),
    "living_expense_coverage": ("eligibility_evidence", "DESCRIPTIVE", "Preserved as unparsed text."),
    "travel_coverage": ("eligibility_evidence", "DESCRIPTIVE", "Preserved as unparsed text."),
    "accommodation_coverage": ("eligibility_evidence", "DESCRIPTIVE", "Preserved as unparsed text."),
    "application_fee": ("legacy_metadata.application_fee", "APPLICATION INFORMATION", "Preserved; not interpreted."),
    "application_deadline": ("deadline", "APPLICATION INFORMATION", "ISO dates parsed; rolling/text values remain unknown with warning."),
    "scholarship_duration": ("legacy_metadata.scholarship_duration", "DESCRIPTIVE", "Preserved source value."),
    "number_of_awards": ("legacy_metadata.number_of_awards", "DESCRIPTIVE", "Preserved source value."),
    "documents_required": ("eligibility_evidence", "DESCRIPTIVE / ELIGIBILITY", "Preserved as UNPARSED text."),
    "eligibility_criteria": ("eligibility_evidence", "DESCRIPTIVE / ELIGIBILITY", "Preserved as UNPARSED text."),
    "selection_criteria": ("eligibility_evidence", "DESCRIPTIVE", "Preserved as UNPARSED text."),
    "description": ("description", "DESCRIPTIVE INFORMATION", "Canonical description."),
    "renewable": ("legacy_metadata.renewable", "DESCRIPTIVE", "Preserved source value."),
    "last_verified": ("legacy_metadata.last_verified_source_value", "SOURCE METADATA", "Preserved source value; does not verify record."),
}